### ISSUE TITLE
[java_http] Remove redundant files

### ISSUE THREAD

**Issue by alex-james-dev** [dart-lang/http#982]
After PR #980 is merged we no longer need [java_http_test.dart](https://github.com/dart-lang/http/blob/067bff3b4727ed8633177010ff12d1121e764861/pkgs/java_http/test/java_http_test.dart), therefore the file will be removed in a future PR ([context](https://github.com/dart-lang/http/pull/980#discussion_r1253693596)).

I'm wondering if we still need the other files generated by the Dart `create` command or can we remove them as well:
- [java_http_base.dart](https://github.com/dart-lang/http/blob/067bff3b4727ed8633177010ff12d1121e764861/pkgs/java_http/lib/src/java_http_base.dart)
- [java_http_example.dart](https://github.com/dart-lang/http/blob/067bff3b4727ed8633177010ff12d1121e764861/pkgs/java_http/example/java_http_example.dart)

As we spoke about during the GSoC Sync meeting on 30th June, we plan to eventually include the same example from [cupertino_http](https://github.com/dart-lang/http/tree/9833a20b257d3ffd9503e530a841f06688340d21/pkgs/cupertino_http/example) and [cronet_http](https://github.com/dart-lang/http/tree/9833a20b257d3ffd9503e530a841f06688340d21/pkgs/cronet_http/example) but which uses `JavaClient`. Should I create a new GitHub issue for including an example in `package:java_http`?

java_http :coffee: team:
@brianquinlan 
@HosseinYousefi 

Tracking issue: #957

**Comment by brianquinlan** [comment]
`java_http_base.dart` can go.
`java_http_example.dart` should probably be replaced with the same example as used in `cronet_http`/`cupertino_http`.

**Comment by alex-james-dev** [comment]
I agree, it's a good idea to replace the example in `java_http_example.dart` with the same example used in `cronet_http`/`cupertino_http`.

`java_http_example.dart` currently uses code from `java_http_base.dart`, so we can remove `java_http_base.dart` after we've replaced the example code in `java_http_example.dart` with the sample example from `cronet_http`/`cupertino_http`.

## Tasks
- [ ] Remove `java_http_test.dart`.
- [ ] Replace the example in `java_http_example.dart` with the same example used in [`cronet_http`](https://github.com/dart-lang/http/tree/e8e35db0d19cc7cb30163874c2e63b818864fbee/pkgs/cronet_http/example) / [`cupertino_http`](https://github.com/dart-lang/http/tree/e8e35db0d19cc7cb30163874c2e63b818864fbee/pkgs/cupertino_http/example).
- [ ] Remove `java_http_base.dart`.
